name: Periodic HealthCheck

on:
  push:
    branches:
      - readme-branch

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v1.5
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex-cicd-app.herokuapp.com/health|https://pokedex-cicd-app.herokuapp.com/pokemon/version
          max-attempts: 3
          retry-delay: 3s
