name: Periodic HealthCheck

on:
  push:
    branches:
      - readme-branch

jobs:
  health_check_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Check the deployed service URL
        uses: jtalk/url-health-check-action@v2
        with:
          # Check the following URLs one by one sequentially
          url: https://pokedex-cicd-app.herokuapp.com/|https://pokedex-cicd-app.herokuapp.com/pokemon/charmander

          max-attempts: 3 # Optional, defaults to 1
          # Delay between retries
          retry-delay: 5s # Optional, only applicable to max-attempts > 1

